### ISSUE TITLE
loader_schedule not working

### ISSUE THREAD

**Issue by duzvik** [logstash-plugins/logstash-filter-jdbc_static#21]
According to https://github.com/logstash-plugins/logstash-filter-jdbc_static/issues/8
the correct place to put loader_schedule settings is inside loaders section.

```
loaders => [
      {
        id => "remote-data"
        query => "select ......"
        local_table => "guids"
        loader_schedule => "*/5 * * * *"
      }
    ]
```

I'm using 
```
tcpdump  port 3306
``` 
to catch MySQL connections.  
I see data traffic to MySQL server only once, after a restart of logstash.

**Comment by guyboertje** [comment]
PR #19 will fix this.

**Comment by guyboertje** [comment]
`loader_schedule` should not be in each loader definition. We have not implemented separate schedulers per loader. At this time scheduling applies to all loaders. This is meant to be "static" in that the remote db should not be changing very often i.e. reference data - meaning it "should" be ok to reload all the remote data once a day for example.

**Comment by guyboertje** [comment]
As per #24, user confirms scheduling is now operational in v1.0.2. Closing.
