### ISSUE TITLE
can't use LIKE statement on local_lookups

### ISSUE THREAD

**Issue by IzekChen** [logstash-plugins/logstash-filter-jdbc_static#46]
Here is my query:
query => "select * from host_info WHERE Name LIKE :hostname "

But seems like it is not working.
Is it supported? or just format wrong

**Comment by guyboertje** [comment]
I have used it in testing.

https://db.apache.org/derby/docs/10.1/ref/rrefjdbc28456.html
https://db.apache.org/derby/docs/10.0/manuals/tuning/perf96.html

because `:hostname` will be made into a single quoted string during substitutions, you need to add the `%` wildcards in the `parameters` setting and not in the statement. That is, the `%` character needs to be in the value before it is quoted and substituted into the statement, e.g. `"parameters" => {"hostname" => "%%{[hostname]}"}`.
This has the effect of prefixing the value of the `hostname` field with the `%` character.

**Comment by IzekChen** [comment]
is there any way I can debug or try to simulator the query.
Seems like not working


This is my config
    local_lookups => [
      {
        query => "select * from host_info WHERE Name LIKE :hostname "
        parameters => { hostname => "%%{[hostname]}" }
        target => "host_name"
      }
    ]

The hostname I post in is "tng412", but the data in the local db is "TNG412"

When the host name is TNG412, it successfully lookup
```json
  {
      "@version" => "1",
     "host_name" => [
        [0] {
                 "description" => "TNG",
            "shortdescription" => "10.62.240.104",
                      "status" => "0",
                        "name" => "TNG412"
        }
    ],
       "headers" => {
         "request_method" => "POST",
              "http_host" => "localhost:8851",
        "http_user_agent" => "curl/7.29.0",
           "request_path" => "/",
         "content_length" => "21",
            "http_accept" => "*/*",
           "http_version" => "HTTP/1.1",
           "content_type" => "application/json"
    },
      "hostname" => "TNG412",
    "@timestamp" => 2019-02-27T09:00:41.138Z,
          "host" => "127.0.0.1"
}
```
But for "tng412", it just empty
```json
{
      "@version" => "1",
     "host_name" => [],
       "headers" => {
         "request_method" => "POST",
              "http_host" => "localhost:8851",
        "http_user_agent" => "curl/7.29.0",
           "request_path" => "/",
         "content_length" => "21",
            "http_accept" => "*/*",
           "http_version" => "HTTP/1.1",
           "content_type" => "application/json"
    },
      "hostname" => "tng412",
    "@timestamp" => 2019-02-27T09:02:01.957Z,
          "host" => "127.0.0.1"
}
```

**Comment by guyboertje** [comment]
Apache Derby (JavaDB) is case sensitive.
You can try `WHERE UPPER(name) LIKE UPPER(:hostname)`

**Comment by IzekChen** [comment]
Cool! I am just thinking maybe I should force uppercase  or lowercase the field to lookup.
Appreciate it.
